# Generated by Django 4.0 on 2021-12-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_for_day', models.FloatField()),
                ('numb_rooms', models.IntegerField()),
                ('numb_people', models.IntegerField()),
                ('double_bed', models.IntegerField()),
                ('single_bed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=6)),
                ('street_house_numb', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('web_www', models.CharField(max_length=50)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('percent_advance_payment', models.IntegerField()),
                ('numb_of_days_advance_payment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(verbose_name='arrival date')),
                ('departure_date', models.DateTimeField(verbose_name='departure date')),
                ('total_price', models.FloatField()),
                ('advance_payment', models.FloatField()),
                ('advance_payment_date', models.DateTimeField(verbose_name='advance payment date')),
                ('payment_status', models.CharField(max_length=30)),
                ('add_info', models.CharField(max_length=250)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.accomodation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.client')),
            ],
        ),
        migrations.AddField(
            model_name='accomodation',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.object'),
        ),
    ]
