# Generated by Django 4.0 on 2021-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='advance_payment_date',
            field=models.DateField(verbose_name='advance payment date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrival_date',
            field=models.DateField(verbose_name='arrival date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(verbose_name='departure date'),
        ),
    ]
