# Generated by Django 4.0 on 2021-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_reservation_advance_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='add_info',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
