# Generated by Django 4.0 on 2021-12-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_reservation_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Accommodation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='accomodation',
            new_name='accommodation',
        ),
    ]
