# Generated by Django 4.0 on 2021-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='street_house_numb',
        ),
        migrations.AlterField(
            model_name='object',
            name='zip_code',
            field=models.CharField(max_length=30),
        ),
    ]
