# Generated by Django 4.0 on 2021-12-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_object_street_house_numb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='street_house_numb',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='object',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
