# Generated by Django 4.0 on 2021-12-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_object_street_house_numb_alter_object_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='object',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='object',
            name='numb_of_days_advance_payment',
        ),
        migrations.RemoveField(
            model_name='object',
            name='percent_advance_payment',
        ),
    ]
