# Generated by Django 4.0 on 2021-12-17 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_object_check_in_remove_object_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='check_in',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='check_out',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='numb_of_days_advance_payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='percent_advance_payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='street_house_numb',
            field=models.CharField(max_length=30),
        ),
    ]
