# Generated by Django 4.0 on 2021-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
