# Generated by Django 4.0 on 2022-01-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_reservation_object_alter_reservation_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='advance_payment_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
    ]
