# Generated by Django 4.0 on 2022-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_reservation_advance_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('PaidAP', 'Paidap'), ('Unpaid', 'Unpaid')], default='Paid', max_length=10),
        ),
    ]
